### ISSUE TITLE
Could you please add clear playlist functionality ?

### ISSUE THREAD

**Issue by sebastiande** [pfischi/shSonos#71]
If you want to play a alarm (ex. fire alarm) over all sonos speakers in loop mode, there is no method to clear the playlist first. If there are other music in it it will be played also ...

Thank you very much!

**Comment by pfischi** [comment]
I'll be back after a long time without internet access. I'll take a look at this functionality.

**Comment by pfischi** [comment]
coming soon ...

**Comment by pfischi** [comment]
Hi, i added the 'clear_queue' functionality in https://github.com/pfischi/shSonos/commit/38d6d702c408b8cf590d3f0103e38d53361f541b. You can download the latest release v0.8.
